<a href="https://colab.research.google.com/github/Subhas-1130/Subhas-demo/blob/main/Copy_of_ML_1st_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix


In [ ]:
# Load the Iris dataset (or use your dataset)
data = load_iris()
X = data.data
y = data.target

In [ ]:
# Split dataset into train and test sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Gaussian Naive Bayes
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred_gnb = gnb.predict(X_test)

In [ ]:
# Multinomial Naive Bayes (requires non-negative features)
mnb = MultinomialNB()
mnb.fit(X_train, y_train)
y_pred_mnb = mnb.predict(X_test)

In [ ]:
# Bernoulli Naive Bayes (requires binary features, so we'll modify the data)
X_train_bin = np.where(X_train > 0, 1, 0)  # Convert to binary
X_test_bin = np.where(X_test > 0, 1, 0)

bnb = BernoulliNB()
bnb.fit(X_train_bin, y_train)
y_pred_bnb = bnb.predict(X_test_bin)

In [ ]:
# Calculate metrics for each classifier
def calculate_metrics(y_test, y_pred):
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='macro', zero_division=0)
    recall = recall_score(y_test, y_pred, average='macro', zero_division=0)
    f1 = f1_score(y_test, y_pred, average='macro', zero_division=0)
    cm = confusion_matrix(y_test, y_pred)

    return accuracy, precision, recall, f1, cm

In [ ]:
# Gaussian Naive Bayes metrics
accuracy_gnb, precision_gnb, recall_gnb, f1_gnb, cm_gnb = calculate_metrics(y_test, y_pred_gnb)
print("Gaussian Naive Bayes Results")
print(f"Accuracy: {accuracy_gnb:.4f}")
print(f"Precision: {precision_gnb:.4f}")
print(f"Recall: {recall_gnb:.4f}")
print(f"F1-Score: {f1_gnb:.4f}")
print("Confusion Matrix:")
print(cm_gnb)

Gaussian Naive Bayes Results
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1-Score: 1.0000
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [ ]:

# Multinomial Naive Bayes metrics
accuracy_mnb, precision_mnb, recall_mnb, f1_mnb, cm_mnb = calculate_metrics(y_test, y_pred_mnb)
print("\nMultinomial Naive Bayes Results")
print(f"Accuracy: {accuracy_mnb:.4f}")
print(f"Precision: {precision_mnb:.4f}")
print(f"Recall: {recall_mnb:.4f}")
print(f"F1-Score: {f1_mnb:.4f}")
print("Confusion Matrix:")
print(cm_mnb)


Multinomial Naive Bayes Results
Accuracy: 0.9000
Precision: 0.9167
Recall: 0.9091
F1-Score: 0.8997
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]


In [ ]:
# Bernoulli Naive Bayes metrics
accuracy_bnb, precision_bnb, recall_bnb, f1_bnb, cm_bnb = calculate_metrics(y_test, y_pred_bnb)
print("\nBernoulli Naive Bayes Results")
print(f"Accuracy: {accuracy_bnb:.4f}")
print(f"Precision: {precision_bnb:.4f}")
print(f"Recall: {recall_bnb:.4f}")
print(f"F1-Score: {f1_bnb:.4f}")
print("Confusion Matrix:")
print(cm_bnb)


Bernoulli Naive Bayes Results
Accuracy: 0.3000
Precision: 0.1000
Recall: 0.3333
F1-Score: 0.1538
Confusion Matrix:
[[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]
